### ISSUE TITLE
[chore] 프로젝트 세팅 

### ISSUE THREAD

**Issue by yhj1129** [3DAsset-eCommerce/3D-BE#1]
## Description

>서비스 구현 전 세팅

## Tasks

- [x] 에러 처리
- [x] 로그 처리
- [x] 의존성 설정 
- [x] 기본 util 설정 
- [x] Security 기본 설정
- [x] 기본 필터
- [x] web MVC 설정 
- [x] Rest API 설정 
- [x] 기본 엔티티 설정
- [x] 세션 유저 설정(email로)
- [x] 더미 데이터 설정 
- [x] authorization 처리
