### ISSUE TITLE
[feat] 관리자 에셋 비활성화

### ISSUE THREAD

**Issue by yhj1129** [3DAsset-eCommerce/3D-BE#101]
## Description

> 관리자가 등록된 에셋을 삭제하는 서비스

## Tasks

- [x] endPoint로 관리자 확인
- [x] 삭제할 에셋id 받기 
- [x] 에셋의 ststus를 비활성 상태로 update
~~- [ ] Controller Test~~
- [x] Service Test
~~- [ ] Repository Test~~
- [x] Integration Test
