### ISSUE TITLE
[feat] 실제 에셋 다운로드

### ISSUE THREAD

**Issue by JasonSong97** [3DAsset-eCommerce/3D-BE#12]
## Description

> 실제 에셋 다운로드 기능

## Tasks

- [ ] 유효성 검사
- [ ] 동일 유저인지 확인 - DB 조회
- [ ] 에셋 다운로드 비즈니스 로직 구현
- [ ] 압축 비즈니스 로직 구현
- [ ] 컨트롤러 테스트
- [ ] 서비스 테스트
- [ ] 레포지토리 테스트
- [ ] 통합 테스트
