### ISSUE TITLE
[feat] 상위 카테고리별 에셋 조회 

### ISSUE THREAD

**Issue by realgreatcode** [3DAsset-eCommerce/3D-BE#14]
## Description

>상위 카테고리별 에셋을 조회하고 응답한다. 

## Tasks

- [x] 비로그인 사용자와 로그인 사용자를 구분한다.
- [x] 상위 카테고리별 에셋 조회를 구현한다
- [x] 로그인 사용자이면 에셋에 찜한 상태, 장바구니 상태를 포함시킨다.
- [x] 정렬 : 에셋 릴리즈날짜 기준 내림차순
- [x] 페이지네이션 : 기본 page=0 & size=28
- [ ] Controller Test
- [ ] Service Test
- [ ] Repository Test
- [x] Integration Test
