### ISSUE TITLE
[feat] 카테고리별 이름, 에셋 수, 태그리스트

### ISSUE THREAD

**Issue by realgreatcode** [3DAsset-eCommerce/3D-BE#35]
## Description

>카테고리별 이름, 에셋의 수, 태그리스트를 응답한다.
>카테고리(이름, 에셋의 수, 태그리스트) 리스트가 있고,
>카테고리마다 서브카테고리(이름, 에셋 수, 태그리스트) 리스트가 있어야 한다.

## Tasks

- [x] 컨트롤러 메소드 구현
- [x] 응답DTO 생성
- [x] 레포지토리 메소드 구현
- [x] 서비스 메소드 구현
- [x] 통합테스트
- [x] 응답데이터에 카테고리별, 서브카테고리별 태그리스트 추가 요청받음 & 카테고리, 서브카테고리, 태그 관련 ERD 수정
- [x] 컨트롤러 수정
- [x] 서비스 수정
- [x] 레포지토리 수정
- [x] DTO 수정
- [x] 통합테스트 수정
