### ISSUE TITLE
[feat] 회원가입

### ISSUE THREAD

**Issue by ji-hoooon** [3DAsset-eCommerce/3D-BE#39]
## Description

>> 회원가입하는 API

## Tasks

- [ ] 회원가입 컨트롤러 메서드 구현
- [ ] SignUpIn/OutDTO 구현
- [ ] 회원가입 서비스 메서드 구현
- [ ] VerifiedCode 제거 후, 엔티티에 추가
- [ ] 회원가입로직 내에서 인증이메일 전송 (인증코드 전송방식 구현불가)

## References

- [Google](https://www.google.com/)

**Comment by ji-hoooon** [comment]
> ## Description
> > > 회원가입하는 API
> 
> ## Tasks
> * [ ]  회원가입 컨트롤러 메서드 구현
> * [ ]  SignUpIn/OutDTO 구현
> * [ ]  회원가입 서비스 메서드 구현
> * [ ]  VerifiedCode 제거 후, 엔티티에 추가
> * [ ]  회원가입로직 내에서 인증이메일 전송 (인증코드 전송방식 구현불가)
> 
> ## References
> * [Google](https://www.google.com/)
