### ISSUE TITLE
[setting] JaCoCo 설정

### ISSUE THREAD

**Issue by yhj1129** [3DAsset-eCommerce/3D-BE#98]
## Description

> 테스트 커버리지를 확인하기 위한 JaCoCo를 설정

## Tasks

- [ ] JaCoCo 플러그인 추가
- [ ] Gradle task 설정
- [ ] 코드 준비와 테스트 실행
- [ ] 여러 task를 함께 실행
- [ ] test task 실행 시 JaCoCo task 실행하도록 설정
- [ ] 커버리지 기준 설정
- [ ] JaCoCo 테스트에서 제외하기

## References

- [우아한 형제들 기술블로그](https://techblog.woowahan.com/2661/)
